In [18]:
# 패키지 불러오기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd

In [19]:
# 데이터 셋 로딩
iris = load_iris()

# iris feature
iris_data = iris.data

# iris target
iris_label = iris.target

# data확인.
print(iris_data,'\n',iris_label)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [20]:
# train, test split
x_train, x_test, y_train, y_test = train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

In [21]:
# decision tree 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(x_train,y_train)

# 예측 수행
pred = dt_clf.predict(x_test)

# 평가 수행
print(accuracy_score(y_test,pred))

0.9333333333333333


In [22]:
# k-fold cross validtaion
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=56)

# 5개의 fold set으로 분리하는 kfold 객체와 fold set별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []

n_iter = 0

for train_index, test_index in kfold.split(features):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)

    accuracy = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)

print(np.mean(cv_accuracy))

0.9199999999999999


In [23]:
# stratified k-fold
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

dt_clf = DecisionTreeClassifier(random_state=56)

skfold = StratifiedKFold(3)
cv_accuracy = []

for train_index, test_index in skfold.split(features,label):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)

    accuracy = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)

print(np.mean(cv_accuracy))

0.9733333333333333


In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=56)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도, cv = 3
scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차검증별 정확도 : ',np.round(scores,4))
print('평균 검증 정확도 : ',np.round(np.mean(scores)),4)

교차검증별 정확도 :  [0.98 0.94 1.  ]
평균 검증 정확도 :  1.0 4


In [25]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import pandas as pd

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=56)

dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1,2,3], 'min_samples_split' : [2,3]}

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit= True)
grid_dtree.get_params().keys()

grid_dtree.fit(X_train,y_train)

scores = pd.DataFrame(grid_dtree.cv_results_)
scores[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.658333                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.658333                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.925000                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.925000                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.950000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.950000                1   

   split0_test_score  split1_test_score  split2_test_score  
0               0.65               0.65              0.675  
1               0.65               0.65              0.675  
2               0.90               0.95              0.925  
3               0.90               0.95              0.925  
4               0.90               1.00              0.950  
5               0.90               1.00              0.950

In [26]:
print('최적 파라미터 : ',grid_dtree.best_params_)
print('최고 정확도 : {0:.4f}'.format(grid_dtree.best_score_))

최적 파라미터 :  {'max_depth': 3, 'min_samples_split': 2}
최고 정확도 : 0.9500


In [27]:
from sklearn.metrics import accuracy_score

# refit으로 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# 최적파라미터로 학습된 모델로 예측
pred = estimator.predict((X_test))
print('테스트 정확도 : {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 정확도 : 0.9333


In [28]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['tv','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder 객체를 생성한 후 fit()와 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ',labels)

인코딩 변환값 :  [0 1 4 5 3 3 2 2]


In [29]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['tv','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 레이블 인코딩 실행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# 원 핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

# 결과 출력
print(oh_labels.toarray())
print(oh_labels.shape)
print(labels)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)
[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


In [30]:
import pandas as pd

df = pd.DataFrame({'item':['tv','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_tv  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0