In [2]:
# TFAutoModelForCausalLM 텐서플로 전용 패키지로, 사전학습된 모형을 가지고 앞의 단어를 보고 뒤의 하나를 맞추는 언어 모형
import tensorflow as tf
from transformers import TFAutoModelForCausalLM, AutoTokenizer

In [3]:
tokenizer = AutoTokenizer.from_pretrained("xlnet-base-cased")

In [4]:
model = TFAutoModelForCausalLM.from_pretrained("xlnet-base-cased")

All model checkpoint layers were used when initializing TFXLNetLMHeadModel.

All the layers of TFXLNetLMHeadModel were initialized from the model checkpoint at xlnet-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetLMHeadModel for predictions without further training.


In [5]:
tokenizer.vocab_size

32000

In [6]:
vocab = tokenizer.get_vocab()
vocab

{'lip': 8562,
 '▁adventure': 6693,
 'mala': 15988,
 '▁generous': 8671,
 'last': 11648,
 '▁user': 1930,
 '▁Boys': 10638,
 'witt': 23232,
 'Eye': 26113,
 'proclaimed': 30111,
 'hua': 9742,
 '▁teachers': 2983,
 '▁Sixteen': 27044,
 'iyah': 16444,
 '▁meetings': 3049,
 '▁McCl': 17586,
 'ups': 8296,
 '▁Yusuf': 26741,
 'els': 8377,
 '▁racist': 15385,
 'nova': 10503,
 '▁Carrie': 21650,
 '▁Bullock': 29905,
 '▁Blair': 4778,
 '▁Monastery': 26758,
 '▁beverage': 19275,
 'dy': 2087,
 '▁refining': 24232,
 '▁isolated': 6810,
 'leading': 14261,
 '▁redesign': 22736,
 '▁scratch': 12079,
 '▁Guild': 13062,
 '▁warships': 23176,
 '▁NGO': 16678,
 '’': 165,
 '▁Eugen': 25527,
 'security': 11805,
 '▁holdings': 15514,
 '▁bask': 30769,
 'HG': 26073,
 'help': 15732,
 '▁Af': 13935,
 '▁dishonest': 27449,
 'miami': 26897,
 '▁August': 707,
 'odor': 9314,
 '▁makers': 7928,
 'late': 7806,
 'pine': 10213,
 '▁fingerprint': 18267,
 '▁entice': 25222,
 '▁taboo': 28527,
 '▁waves': 6555,
 '▁Once': 1977,
 'We': 236,
 '▁bags': 580

In [7]:
id2word = {i : word for word,i in vocab.items()}

In [8]:
id2word

{8562: 'lip',
 6693: '▁adventure',
 15988: 'mala',
 8671: '▁generous',
 11648: 'last',
 1930: '▁user',
 10638: '▁Boys',
 23232: 'witt',
 26113: 'Eye',
 30111: 'proclaimed',
 9742: 'hua',
 2983: '▁teachers',
 27044: '▁Sixteen',
 16444: 'iyah',
 3049: '▁meetings',
 17586: '▁McCl',
 8296: 'ups',
 26741: '▁Yusuf',
 8377: 'els',
 15385: '▁racist',
 10503: 'nova',
 21650: '▁Carrie',
 29905: '▁Bullock',
 4778: '▁Blair',
 26758: '▁Monastery',
 19275: '▁beverage',
 2087: 'dy',
 24232: '▁refining',
 6810: '▁isolated',
 14261: 'leading',
 22736: '▁redesign',
 12079: '▁scratch',
 13062: '▁Guild',
 23176: '▁warships',
 16678: '▁NGO',
 165: '’',
 25527: '▁Eugen',
 11805: 'security',
 15514: '▁holdings',
 30769: '▁bask',
 26073: 'HG',
 15732: 'help',
 13935: '▁Af',
 27449: '▁dishonest',
 26897: 'miami',
 707: '▁August',
 9314: 'odor',
 7928: '▁makers',
 7806: 'late',
 10213: 'pine',
 18267: '▁fingerprint',
 25222: '▁entice',
 28527: '▁taboo',
 6555: '▁waves',
 1977: '▁Once',
 236: 'We',
 5803: '▁bags

In [9]:
sequence = f"Once upon a time, there was,,,"

In [10]:
input_ids = tokenizer.encode(sequence,return_tensors="tf")

In [11]:
input_ids

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[1977,  975,   24,   92,   19,  105,   30,   19,   19,   19,    4,
           3]])>

In [12]:
id2word[1977]

'▁Once'

In [13]:
result = model(input_ids)

In [14]:
logits = result[0]

In [15]:
logits

<tf.Tensor: shape=(1, 12, 32000), dtype=float32, numpy=
array([[[-17.762897, -33.77447 , -33.579697, ..., -29.58265 ,
         -29.765543, -32.341812],
        [-18.557228, -36.325657, -36.0391  , ..., -31.620697,
         -27.772741, -33.11712 ],
        [-18.098015, -37.18671 , -37.017693, ..., -32.138035,
         -27.441545, -30.943308],
        ...,
        [-19.678535, -39.910053, -39.841484, ..., -32.80705 ,
         -30.68355 , -36.15405 ],
        [-16.214714, -37.23381 , -36.99289 , ..., -30.086628,
         -27.410667, -32.71711 ],
        [-13.108336, -33.315643, -32.85415 , ..., -27.609539,
         -23.538055, -28.555574]]], dtype=float32)>

In [16]:
logits.shape

TensorShape([1, 12, 32000])

In [18]:
next_token_logits = logits[:,-1,:]

In [21]:
next_token_logits

<tf.Tensor: shape=(1, 32000), dtype=float32, numpy=
array([[-13.108336, -33.315643, -32.85415 , ..., -27.609539, -23.538055,
        -28.555574]], dtype=float32)>

In [22]:
tf.nn.softmax(next_token_logits)

<tf.Tensor: shape=(1, 32000), dtype=float32, numpy=
array([[5.4215951e-05, 9.0824998e-14, 1.4408869e-13, ..., 2.7310839e-11,
        1.6016142e-09, 1.0604181e-11]], dtype=float32)>

In [23]:
top = tf.math.top_k(next_token_logits,k=10)

In [24]:
top

TopKV2(values=<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-5.7981563, -5.830226 , -6.0612893, -6.1215324, -6.206487 ,
        -6.217775 , -6.532774 , -6.589526 , -6.663578 , -6.9537106]],
      dtype=float32)>, indices=<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[292,  19, 105, 975,  17,  36, 194, 176,  30,  38]])>)

In [25]:
top.indices

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[292,  19, 105, 975,  17,  36, 194, 176,  30,  38]])>

In [26]:
for i in top.indices[0].numpy().tolist():
    print(id2word[i])

▁again
,
▁there
▁upon
▁
▁it
▁still
▁even
▁was
▁at
