In [2]:
# NumPy
import numpy as np

In [3]:
# 일반 리스트
[1,4,2,5]

[1, 4, 2, 5]

In [5]:
# numpy array
np.array([1,4,2,5])

array([1, 4, 2, 5])

In [6]:
# 자료형이 다를경우 상위 자료형으로 바뀜
np.array([1,4,2.4,5])

array([1. , 4. , 2.4, 5. ])

In [7]:
# dtype을 통해 원하는 자료형으로 만들 수 있음.
np.array([1,4,2.4,5],dtype=int)

array([1, 4, 2, 5])

In [8]:
np.array([1,'a',3,4.5])

array(['1', 'a', '3', '4.5'], dtype='<U32')

In [10]:
# 이중 리스트
np.array([[1,2,3],[4,5,6],[7,8,9,]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [12]:
# 2행 3열로 만듦. 0으로 촉시화
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
# 1로 초기화.
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
# (3,2) matrix를 3.14로 초기화.
np.full((3,2),3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [16]:
# 0부터 20까지 순차적으로 array생성. 파이썬에서는 0~20이면 19까지만임.
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# 0부터 20까지 2씩 증가
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# -1이면 역순
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
# 데이터를 정확하게 쪼개서 발생.
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# 난수 발생
np.random.random(10)

array([0.40631685, 0.09229559, 0.64153879, 0.90955906, 0.23664465,
       0.31909774, 0.78022157, 0.25542181, 0.07589342, 0.98773086])

In [22]:
# 2차원으로 데이터 뽑기
np.random.random((3,2))

array([[0.17444829, 0.00985323],
       [0.02373732, 0.32767132],
       [0.37949667, 0.61909975]])

In [25]:
# 범위 지정해서 난수 발생
np.random.normal(10000,2000,(3,3))

array([[ 6785.17832983,  7457.77269853, 10009.15281648],
       [13695.16113507,  7905.47906049,  9968.46671403],
       [ 6622.09659486,  6192.03129976, 12304.53259249]])

In [26]:
# normal함수는 평균(0), 표준편차(1)인 난수를 발생시킴. 괄호안은 지정값.
np.random.normal(0,1,10)

array([-1.60646791, -0.46765229,  0.29773347,  0.04985512,  0.00464772,
        0.21622808,  0.65057414, -0.097256  , -1.17214978,  0.3870534 ])

In [27]:
# 1~37까지 랜덤하게 정수뽑기
np.random.randint(1,37,(4,3))

array([[28, 18, 28],
       [29, 13,  6],
       [33, 21, 20],
       [25, 16, 31]])

In [28]:
x = np.arange(1,11)
y = np.arange(11,21)

In [29]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [34]:
# x+y와 동일
np.add(x,y)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [36]:
np.abs(x-y)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [37]:
# 지수
np.exp2(x)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [38]:
# y^x 연산
np.power(y,x)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

In [39]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [40]:
x = np.array([70,80,90,100],dtype=np.int64)

In [41]:
np.sum(x)

340

In [42]:
x.sum()

340

In [43]:
x.mean()

85.0

In [44]:
np.mean(x)

85.0

In [45]:
# 전체를 다 곱함
np.prod(x)

50400000

In [49]:
np.max(x)

100

In [47]:
# 최근값의 인덱스를 출력함.
np.argmax(x)

3

In [52]:
# 중앙값.
np.median(x)

85.0